// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk0DwOg5fr9-4ZndVqHTnfJwOibWAl8Iw',
    appId: '1:645427572355:web:027df2a3a2238fc80cb5b6',
    messagingSenderId: '645427572355',
    projectId: 'healthmateai-1450c',
    authDomain: 'healthmateai-1450c.firebaseapp.com',
    storageBucket: 'healthmateai-1450c.firebasestorage.app',
    measurementId: 'G-SM5YQ0WETD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK5A5oZp4UYfkfM_7rVVVWCmBPGeqVsLM',
    appId: '1:645427572355:android:52a0a663b9f10c630cb5b6',
    messagingSenderId: '645427572355',
    projectId: 'healthmateai-1450c',
    storageBucket: 'healthmateai-1450c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdzOGYS0e2sUX-YEETmi3tSKoCIOzuoPs',
    appId: '1:645427572355:ios:7e4d8de46bfc90840cb5b6',
    messagingSenderId: '645427572355',
    projectId: 'healthmateai-1450c',
    storageBucket: 'healthmateai-1450c.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
